export const UPDATE_SCREEN_SIZE = 'UPDATE_SCREEN_SIZE'

export const ADD_PLAYER_TO_GAME = 'ADD_PLAYER_TO_GAME'
export const UPDATE_PLAYER_POSITION = 'UPDATE_PLAYER_POSITION'

export const CREATE_NEW_USER = 'CREATE_NEW_USER'
export const SET_USERNAME = 'SET_USERNAME'
